name: Deploy to Prod
on:
  push:
    branches: master

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:                  
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
             cd /var/www/team-scoreboard
             git pull
             systemctl restart teamscoreboardapi.service 
